### ISSUE TITLE
Enums in joins are not treated as nullable

### ISSUE THREAD

**Issue by johanbrandhorst** [kyleconroy/sqlc#1157]
### Version

1.9.0

### What happened?

Support for nullable columns in joins were added in v1.9.0. Unfortunately, it appears this doesn't extend to the auto-generated enum types. As can be seen in the generated Go types, the `ListBooksRow` contains an `sql.NullString`, but the enum type is not similarly nullable.

There's a bit of a design discussion to be had around what the best way to handle this is, since enums use a custom type. Perhaps a pointer would be enough, so that it could be null?

Related to #374

### Database schema

```sql
CREATE TABLE authors (
  id   BIGSERIAL PRIMARY KEY,
  name TEXT      NOT NULL
);

CREATE TYPE book_type AS ENUM ('hardback', 'softback', 'ebook');

CREATE TABLE books (
  id        BIGSERIAL PRIMARY KEY,
  title     TEXT      NOT NULL,
  book_type book_type NOT NULL,
  author_id BIGINT    NULL        REFERENCES authors(id)
);
```

### SQL queries

```sql
-- name: ListBooks :many
SELECT authors.name, books.title, books.book_type FROM authors
LEFT JOIN books ON authors.id = books.author_id;
```

### Configuration

```yaml
version: 1
packages:
  - path: "tutorial"
    name: "tutorial"
    engine: "postgresql"
    schema: "schema.sql"
    queries: "query.sql"
```

### Playground URL

https://play.sqlc.dev/p/086e386e94012b813b228429fc8067716c2b68e66db27de20699daafdb9d12b9

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment]
Just wanted to thank you for writing up such a complete bug report. The custom Enum types currently don't support NULL. Once they do, the existing JOIN support should "just work".

**Comment by sbres** [comment]
I've created the PR #1485 that should solve this problem.

**Comment by Jille** [comment]
@SnoozeThis https://github.com/kyleconroy/sqlc/issues/1097

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/bq_DKWjbxEI) I will wait until https://github.com/kyleconroy/sqlc/issues/1097 is closed and then add a comment.

**Comment by sgrishanin** [comment]
@kyleconroy hi, is there any traction on this issue? The aforementioned PR #1485 does not fix this particular issue (not sure what it does honestly), when scanning non-nullable enum that's still null as a result of join

**Comment by sbres** [comment]
I've tested the query in the issue on the playground and it is working properly.
Could you please share what is the model and the query you find problems with?

**Comment by johanbrandhorst** [comment]
The original issue does indeed seem to be fixed, thanks!

**Comment by SnoozeThis** [comment]
Resolved.
