### ISSUE TITLE
Support predeclared Go types in type overrides

### ISSUE THREAD

**Issue by ean** [kyleconroy/sqlc#260]
I am using the postgres [citext](https://www.postgresql.org/docs/11.0/citext.html) extension in my code, and would like to map the `citext` type to a `string` value (I am using it with NOT NULL). But this is explicitly forbidden in the override parse code here: https://github.com/kyleconroy/sqlc/blob/79ec91489719ebcef55b61e07b0083821462dfa3/internal/dinosql/config.go#L103 , which requires both a `.` and `/` in the go type.

**Comment by kyleconroy** [comment]
This has been fixed in the latest version of sqlc. The following `sqlc.json` will correctly override `citext` with `string`.

```json
{
  "version": "1",
  "packages": [...],
  "overrides": [
      {
          "postgres_type": "citext",
          "go_type": "string"
      }
  ]
}
```

**Comment by kyleconroy** [comment]
(I posted this prematurely. You'll need to wait about five minutes for the new build to upload)

**Comment by ean** [comment]
That fixed it for me, thanks!

**Comment by abagshaw** [comment]
This doesn't work for me anymore,

My config:
```
version: "1"
packages:
  - name: "db"
    path: "db"
    queries: "./query/"
    schema: "../../db/migrations/"
    engine: "postgresql"
    emit_json_tags: true
    emit_prepared_queries: true
    emit_interface: false
    emit_exact_table_names: false
    emit_empty_slices: false
overrides:
  - db_type: "citext"
    go_type: "string"
```

But my column with `citext` still gets the `interface{}` type 🙁
