### ISSUE TITLE
Type cast in positional function args yields invalid params

### ISSUE THREAD

**Issue by maxhawkins** [kyleconroy/sqlc#520]
```sql
CREATE FUNCTION plus(a integer, b integer) RETURNS integer AS $$
    BEGIN
        RETURN a + b;
    END;
$$ LANGUAGE plpgsql;

-- name: MakeIntervalPositional :one
SELECT plus($1, $2::INTEGER);
```

yields the params struct
```go
type MakeIntervalPositionalParams struct {
	A       int32
	B       int32
	Column3 int32
}
```

With an extra field `Column3`.

The extra field disappears if the INTEGER cast is removed.

**Comment by maxhawkins** [comment]
I'm thinking about working on this one. @kyleconroy Should I do it on dinosql or wait for the new ast stuff to land before adding?

**Comment by kyleconroy** [comment]
The new ast stuff has landed. You should fix this in the `compiler` package. Let me add a configuration option for tests to indicate that the should only be run using the new compiler.

**Comment by maxhawkins** [comment]
OK great. Is the new compiler enabled by default now or do I need to switch the engine in my sqlc.json?

**Comment by kyleconroy** [comment]
The new compiler is [enabled by default](https://github.com/kyleconroy/sqlc/blob/master/internal/cmd/cmd.go#L77) on master.

**Comment by kyleconroy** [comment]
I've added [a configuration file](https://github.com/kyleconroy/sqlc/pull/521) for replay tests that allows you to skip the deprecated parser tests

**Comment by maxhawkins** [comment]
I have a temporary fix for this (#530)

It fixes the duplicate parameter issue but there is still a problem with it not picking up the parameter name from the function. The column is called Column2.

I think to properly address this we would need to refactor `resolveCatalogRefs` to include special handling for FuncCall nodes. Their parameters (even if deeply nested in the AST) need to reference the parent FuncCall, but it's not possible to reach back up the tree to find it inside of `resolveCatalogRefs`.

Here's what the AST looked like for my test case. The ParamRef only knew about its direct parent (the TypeCast node) and wasn't able to see that it was a part of a FuncCall.

```
(*ast.FuncCall)(0xc0000eaaa0)({
     Args: (*ast.List)(0xc00033dde0)({
        Items: ([]ast.Node) (len=2 cap=2) {
         (*pg.TypeCast)(0xc00033de80)({
          Arg: (*pg.ParamRef)(0xc00036e590)({
           Number: (int) 2,
           Location: (int) 230
          }),
       }),
    }),
})
```
